src/WBB/BarBundle/Entity/Tip.php
<?php

namespace WBB\BarBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as JMS;

/**
 * Tip
 *
 * @ORM\Table(name="wbb_tip")
 * @ORM\Entity(repositoryClass="WBB\BarBundle\Repository\TipRepository")
 *
 * @JMS\ExclusionPolicy("all")
 */

class Tip
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @JMS\Expose
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="WBB\UserBundle\Entity\User", inversedBy="tips")
     * @JMS\MaxDepth(1)
     * @JMS\Expose
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="WBB\BarBundle\Entity\Bar", inversedBy="tips")
     */
    private $bar;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     * @JMS\Expose
     */
    private $description;

    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="smallint", nullable=true)
     * @JMS\Expose
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     * @JMS\Expose
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * toString
     */
    public function __toString()
    {
        return $this->getDescription();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set user
     *
     * @param  User $user
     * @return Tip
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set bar
     *
     * @param  Bar $bar
     * @return Tip
     */
    public function setBar($bar)
    {
        $this->bar = $bar;

        return $this;
    }

    /**
     * Get bar
     *
     * @return Bar
     */
    public function getBar()
    {
        return $this->bar;
    }

    /**
     * Set description
     *
     * @param  string $description
     * @return Tip
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set status
     *
     * @param  boolean $status
     * @return Tip
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return boolean
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set createdAt
     *
     * @param  \DateTime $createdAt
     * @return Tip
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param  \DateTime $updatedAt
     * @return Tip
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function getStatusChoices()
    {
        return array(
            0 => 'Pending',
            1 => 'Enabled',
            2 => 'Disabled'
        );
    }

}

src/WBB/BarBundle/Form/TipType.php
<?php

namespace WBB\BarBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use WBB\CoreBundle\Form\DataTransformer\EntityToIDTransformer;

class TipType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $em = $options['em'];

        $builder
            ->add('description', 'textarea', array(
                'required' => false,
                'attr' => array(
                    'class'         => 's-margin-top',
                    'placeholder'   => 'Write your tip ...',
                    'maxlength'     => '250',
                    'minlength'     => '1'
                )
            ))
            ->add($builder->create('bar', 'hidden')->addModelTransformer(new EntityToIDTransformer($em, 'WBBBarBundle', 'Bar')))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver
            ->setDefaults(array(
                'data_class' => 'WBB\BarBundle\Entity\Tip',
                'csrf_protection' => false
            ))
            ->setRequired(array(
                'em',
            ))
            ->setAllowedTypes(array(
                'em' => 'Doctrine\Common\Persistence\ObjectManager',
            ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'wbb_barbundle_tip';
    }
}

src/WBB/BarBundle/Controller/TipsController.php
<?php

namespace WBB\BarBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use WBB\BarBundle\Entity\Tip;
use WBB\BarBundle\Form\TipType;
use WBB\BarBundle\TipsEvents;
use WBB\BarBundle\Event\TipEvent;

/**
 * TipsController
 */
class TipsController extends Controller
{
    /**
     * addAction
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @return JsonResponse
     */
    public function addAction(Request $request)
    {
        $user = $this->getUser();
        if (!$user) {
            return new JsonResponse(array(
                'code'      => 403,
                '_message'  => 'User not authenticated !'
            ));
        }

        $tip = new Tip();
        $tip->setUser($user);
        $popInContent = $this->renderView('WBBBarBundle:Tips/Popin:tipPending.html.twig');
        $isBarExpert = ($this->get('security.context')->isGranted('ROLE_BAR_EXPERT'))?true:false;
        if ($user->getTipsShouldBeModerated() && !$isBarExpert) {
            $tip->setStatus(0);
        } else {
            $tip->setStatus(1);
            $popInContent = $this->renderView('WBBBarBundle:Tips/Popin:tipSubmited.html.twig');
        }

        $form = $this->createForm(new TipType(), $tip, array('em' => $this->container->get('doctrine.orm.entity_manager')));

        if ('POST' === $request->getMethod()) {
            $form->submit($request);
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($tip);
                $em->flush();

                $event = new TipEvent($tip);
                $dispatcher = $this->get('event_dispatcher');
                $dispatcher->dispatch(TipsEvents::TIP_CREATED, $event);

                $tipHTML = $this->renderView('WBBBarBundle:Bar:tip.html.twig', array('tip' => $tip, 'temporary' => true));

                return new JsonResponse(array(
                    'code'          => 200,
                    'message'       => 'Tip submitted!',
                    'tip'           => $tipHTML,
                    'status'        => $tip->getStatus(),
                    'showPopin'     => !$isBarExpert,
                    'popinContent'  => $popInContent
                ));
            } else {
                return new JsonResponse(array('code'=>500, 'message'=>'Unknown Error!'));
            }
        } else {
            return new JsonResponse(array('code'=>403, 'message'=>'You can\'t be here using get!'));
        }
    }

    public function loadTipsAction($barID, $offset = 3, $limit = 8)
    {
        $bar    = $this->container->get('bar.repository')->findOneById($barID);
        $tips   = $this->container->get('tip.repository')->findLatestTips($bar, $offset, $limit);
        $all    = $this->container->get('tip.repository')->findLatestTips($bar, $offset, 0);

        $response['nbResults']  = count($tips);
        $response['difference'] = count($all) - count($tips);
        $response['htmldata']   = $this->renderView('WBBBarBundle:Bar:wbbTips.html.twig', array(
                'bar'       => $bar,
                'tips'      => $tips,
                'offset'    => $offset,
                'limit'     => $limit
            )
        );

        return new JsonResponse($response);
    }

    public function deleteAction($tipId)
    {
        $user = $this->getUser();
        if (!$user) {
            return new JsonResponse(array(
                'code' => 403,
                'message' => 'User not authenticated !'
            ));
        }

        $em = $this->getDoctrine()->getManager();
        $tip = $em->getRepository('WBBBarBundle:Tip')
            ->findOneBy(array('id' => $tipId));

        if (!$tip) {
            return new JsonResponse(array(
                'code' => 404,
                'message' => 'Tip not found !'
            ));
        }

        $user->removeTip($tip);

        $em->persist($user);
        $em->remove($tip);
        $em->flush();

        return new JsonResponse(array(
            'code' => 200,
            'message' => 'Tip deleted !',
            'tipId' => $tipId
        ));
    }
}

src/WBB/BarBundle/Resources/views/Admin/Tip/edit.html.twig
{% extends 'SonataAdminBundle:CRUD:edit.html.twig' %}

{% block actions %}
    <div class="sonata-actions btn-group">
        {% if object.bar and object.bar.slug %}
            <a class="btn sonata-action-element" href="{{ path('wbb_bar_details',{city: object.bar.city.slug, suburb: object.bar.suburb.slug, slug: object.bar.slug}) }}" target="_blank">
                <i class="icon-zoom-in"></i>
                {{ 'link_action_show'|trans({}, 'SonataAdminBundle') }}
            </a>
        {% endif %}
        {% include 'SonataAdminBundle:Button:history_button.html.twig' %}
        {% include 'SonataAdminBundle:Button:acl_button.html.twig' %}
        {% include 'SonataAdminBundle:Button:create_button.html.twig' %}
        {% include 'SonataAdminBundle:Button:list_button.html.twig' %}
    </div>
{% endblock %}

src/WBB/BarBundle/Resources/views/Admin/Tip/list.html.twig
{% extends "SonataAdminBundle:CRUD:base_list.html.twig" %}

{% block list_header %}
    {{ parent() }}
    <div>
        <a href="{{ url('admin_wbb_bar_tip_list') ~ '?filter[status][value]=0' }}" class="btn">Pending tips</a>
        <a href="{{ url('admin_wbb_bar_tip_list') ~ '?filter[_sort_order]=DESC&filter[_sort_by]=id' }}" class="btn">Latest tips</a>
        <a href="{{ url('admin_wbb_bar_tip_list') ~ '?wbbexpert=1' }}" class="btn">Expert's tips</a>
    </div>
    <br/>
{% endblock %}

src/WBB/BarBundle/Resources/views/Admin/Tip/status_field.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    <div class="btn-group status-field-{{ object.id }}">
        <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" id="label_status_{{ object.id }}">
            {{ object.statusChoices[object.status] }}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% set baseRouteName = admin.baseRouteName %}
            {% for keyChoice, choice in object.statusChoices %}
                <li{% if object.status == keyChoice %} class="active"{% endif %}>
                    <a class="change-status-{{ object.id }}" data-label="{{ choice }}" href="{{ url('sonata_admin_set_object_field_value', {'code': admin.code, '_sonata_admin': admin.code(object), 'objectId': object.id, 'field': 'status', 'value': keyChoice, context: 'list'}) }}">
                        {{ choice|trans({}, admin.translationdomain) }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <script type="text/javascript">
        $(function() {
            $('.status-field-{{ object.id }}').parent().unbind();

            $(".change-status-{{ object.id }}").on('click', function(event) {
                var labelValue = $(this).data('label');
                event.preventDefault();
                $.post($(this).attr('href'), function(response) {
                    if('KO' === response.status) {
                        console.log(response.content)
                    }
                    $('#label_status_{{ object.id }}').html(labelValue+'<span class="caret"></span>');
                });
            });
        });
    </script>
{% endblock %}